---
- name: "Webserver setup"
  hosts: all
  tasks:
    - name: "Install webserver"
      yum:
        name: 
          - httpd
          - firewalld
        state: present

    - name: "Start and enable the service"
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - httpd.service
        - firewalld.service

